#!/bin/sh

#array size
for length in 1000 2000 3000 4000 5000 6000 7000 8000 9000 10000 
do
        echo "Length: " $length
        g++ -Dlength=$length project5.cpp -o project5 -lm -fopenmp
        ./project5
done

