#!/bin/sh

#number of threads:
for NUMT in 1 2 4
do
	echo "NUMT: " $NUMT
	for NUM in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
	do
		echo "NUM: " $NUM
		g++ -DNUMT=$NUMT -DNUM=$NUM project3.cpp -o project3 -lm -fopenmp
		./project3
	done
done

#        echo NUMT = $varT
 #       g++ -DNUMT=$varT project2.cpp -o project2 -lm -fopenmp
  #      ./project2
#done
